# Generated by Django 4.0.5 on 2022-07-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=100)),
                ('core', models.CharField(max_length=100)),
                ('wood', models.CharField(max_length=100)),
                ('maker', models.CharField(max_length=100)),
            ],
        ),
    ]
