# Generated by Django 4.0.6 on 2022-07-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_spell'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizard',
            name='spells',
            field=models.ManyToManyField(to='main_app.spell'),
        ),
    ]
